### PR TITLE
#161438835 Continuous Integrations

### PR DESCRIPTION
**Pull request by Duncanian**
#### What does this PR do?
- Integrate Circle CI to run builds
- Integrate Code climate to report quality and test coverage from Circle CI builds.
- Add the following badges:
   1. Circle CI build badge
   2. Code climate maintainability badge
   3. Code climate test coverage badge

#### What are the relevant pivotal tracker stories?
[#161438835](https://www.pivotaltracker.com/story/show/161438835) Setup integration for circleCI and codeClimate

#### Screenshot
image

### CODE REVIEW

**Review by samuelkubai — APPROVED** [review]
LGTM, you might need to properly setup ESlint to avoid the reformatting changes in your PRs.

**Review by samuelkubai — CHANGES_REQUESTED** [review]
You need to setup the test command in your `package.json`

**Comment by Duncanian** [comment]
I will set up Eslint properly and make sure that reformatting doesn't appear where it shouldn't.

Let me make the changes.

**Comment by Duncanian** [comment]
@samuelkubai , added the test command

**Review by samuelkubai — APPROVED** [review]
LGTM

**Pull request merged**
